# Generated by Django 2.1 on 2021-05-20 20:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='data_created',
            field=models.DateField(default=datetime.datetime(2021, 5, 20, 20, 30, 30, 383826, tzinfo=utc)),
        ),
    ]
