# Generated by Django 2.2.23 on 2021-05-20 20:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_data_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='data_created',
            field=models.DateField(default=datetime.datetime(2021, 5, 20, 20, 33, 6, 12170, tzinfo=utc)),
        ),
    ]
