# Generated by Django 2.2.23 on 2021-05-21 00:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20210520_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='data_created',
            field=models.DateField(default=datetime.datetime(2021, 5, 21, 0, 21, 39, 79679, tzinfo=utc)),
        ),
    ]
