# Generated by Django 2.2.23 on 2021-06-01 00:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20210521_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 0, 58, 45, 736446, tzinfo=utc)),
        ),
    ]
